import apiClient from '../api/axios';
import { LiveTrackingVehicle, FleetSummaryMetrics, ShuttleRoute } from '../types';

const mockFleetVehicles: LiveTrackingVehicle[] = [
  {
    id: 'sht-101',
    shuttleId: 'sht-101',
    vehicleNumber: 'KA-01-EQ-9812',
    model: 'Volvo B11R 45-Seater',
    driverId: 'drv-501',
    driverName: 'Rajesh Kumar',
    driverPhone: '+91 98765 43210',
    routeId: 'rt-101',
    routeName: 'Outer Ring Road Express',
    routeCode: 'ORR-EXP',
    status: 'IN_TRANSIT',
    speedKmH: 48,
    heading: 135,
    fuelLevelPercent: 82,
    batteryLevelPercent: 94,
    currentLocation: {
      lat: 12.9716,
      lng: 77.5946,
      address: 'Near Indiranagar Metro Station, 100ft Rd',
      updatedAt: '2026-07-22 09:12:00',
    },
    nextStop: 'Marathahalli Bridge',
    nextStopEtaMinutes: 6,
    occupancyCount: 38,
    maxCapacity: 45,
    distanceRemainingKm: 14.2,
    estimatedDurationMinutes: 28,
    visitedStopsCount: 3,
    totalStopsCount: 8,
    tripProgressPercent: 42,
    assignedPassengers: [
      { id: 'emp-1', name: 'Alexander Wright', seatNumber: '4A', boardingStop: 'Indiranagar Metro', checkedIn: true },
      { id: 'emp-2', name: 'Sophia Rodriguez', seatNumber: '4B', boardingStop: 'Indiranagar Metro', checkedIn: true },
      { id: 'emp-3', name: 'Marcus Vance', seatNumber: '5A', boardingStop: 'Marathahalli Bridge', checkedIn: false },
    ],
  },
  {
    id: 'sht-102',
    shuttleId: 'sht-102',
    vehicleNumber: 'KA-05-AB-1234',
    model: 'Tata Starbus 32-Seater',
    driverId: 'drv-502',
    driverName: 'Suresh Raina',
    driverPhone: '+91 98123 45678',
    routeId: 'rt-102',
    routeName: 'Whitefield Tech Corridor',
    routeCode: 'WFD-COR',
    status: 'ON_TIME',
    speedKmH: 36,
    heading: 90,
    fuelLevelPercent: 65,
    currentLocation: {
      lat: 12.98,
      lng: 77.72,
      address: 'ITPL Main Road, Hoodi Circle',
      updatedAt: '2026-07-22 09:14:00',
    },
    nextStop: 'ITPL Gate 2',
    nextStopEtaMinutes: 4,
    occupancyCount: 28,
    maxCapacity: 32,
    distanceRemainingKm: 6.8,
    estimatedDurationMinutes: 15,
    visitedStopsCount: 5,
    totalStopsCount: 7,
    tripProgressPercent: 70,
    assignedPassengers: [
      { id: 'emp-4', name: 'Elena Rostova', seatNumber: '2A', boardingStop: 'Hoodi Circle', checkedIn: true },
      { id: 'emp-5', name: 'David Chen', seatNumber: '2B', boardingStop: 'ITPL Gate 2', checkedIn: false },
    ],
  },
  {
    id: 'sht-103',
    shuttleId: 'sht-103',
    vehicleNumber: 'KA-03-CD-5678',
    model: 'Ashok Leyland 40-Seater',
    driverId: 'drv-503',
    driverName: 'Vikram Singh',
    driverPhone: '+91 97654 32109',
    routeId: 'rt-103',
    routeName: 'Electronic City Express',
    routeCode: 'ECI-EXP',
    status: 'IDLE',
    speedKmH: 0,
    heading: 0,
    fuelLevelPercent: 90,
    currentLocation: {
      lat: 12.8399,
      lng: 77.677,
      address: 'Electronic City Phase 1 Depot',
      updatedAt: '2026-07-22 09:00:00',
    },
    nextStop: 'Depot Departure Bay',
    nextStopEtaMinutes: 15,
    occupancyCount: 0,
    maxCapacity: 40,
    distanceRemainingKm: 22.0,
    estimatedDurationMinutes: 40,
    visitedStopsCount: 0,
    totalStopsCount: 6,
    tripProgressPercent: 0,
    assignedPassengers: [],
  },
  {
    id: 'sht-104',
    shuttleId: 'sht-104',
    vehicleNumber: 'KA-04-EF-9012',
    model: 'Eicher Skyline 28-Seater',
    driverId: 'drv-504',
    driverName: 'Anil Kapoor',
    driverPhone: '+91 96543 21098',
    routeId: 'rt-104',
    routeName: 'Manyata Tech Park Shuttle',
    routeCode: 'MTP-SHT',
    status: 'MAINTENANCE',
    speedKmH: 0,
    heading: 0,
    fuelLevelPercent: 40,
    currentLocation: {
      lat: 13.045,
      lng: 77.62,
      address: 'Central Fleet Workshop, Hebbal',
      updatedAt: '2026-07-22 07:30:00',
    },
    nextStop: 'Workshop Bay 3',
    nextStopEtaMinutes: 0,
    occupancyCount: 0,
    maxCapacity: 28,
    distanceRemainingKm: 0,
    estimatedDurationMinutes: 0,
    visitedStopsCount: 0,
    totalStopsCount: 5,
    tripProgressPercent: 0,
    assignedPassengers: [],
  },
  {
    id: 'sht-105',
    shuttleId: 'sht-105',
    vehicleNumber: 'KA-02-GH-3456',
    model: 'Force Traveller 18-Seater',
    driverId: 'drv-505',
    driverName: 'Praveen Sharma',
    driverPhone: '+91 95432 10987',
    routeId: 'rt-105',
    routeName: 'Bellandur Ring Feeder',
    routeCode: 'BLR-FDR',
    status: 'DELAYED',
    speedKmH: 18,
    heading: 270,
    fuelLevelPercent: 55,
    currentLocation: {
      lat: 12.926,
      lng: 77.676,
      address: 'Ecospace Flyover Heavy Traffic',
      updatedAt: '2026-07-22 09:14:30',
    },
    nextStop: 'Ecospace Gate 1',
    nextStopEtaMinutes: 12,
    occupancyCount: 16,
    maxCapacity: 18,
    distanceRemainingKm: 8.5,
    estimatedDurationMinutes: 25,
    visitedStopsCount: 2,
    totalStopsCount: 6,
    tripProgressPercent: 30,
    assignedPassengers: [],
  },
];

export const fleetService = {
  getFleetVehicles: async (): Promise<LiveTrackingVehicle[]> => {
    try {
      const response = await apiClient.get<LiveTrackingVehicle[]>('/fleet/vehicles');
      return response.data;
    } catch {
      return mockFleetVehicles;
    }
  },

  getFleetMetrics: async (): Promise<FleetSummaryMetrics> => {
    try {
      const response = await apiClient.get<FleetSummaryMetrics>('/fleet/metrics');
      return response.data;
    } catch {
      return {
        totalVehicles: mockFleetVehicles.length,
        running: mockFleetVehicles.filter((v) => v.status === 'IN_TRANSIT' || v.status === 'ON_TIME' || v.status === 'DELAYED').length,
        idle: mockFleetVehicles.filter((v) => v.status === 'IDLE').length,
        maintenance: mockFleetVehicles.filter((v) => v.status === 'MAINTENANCE').length,
        offline: 0,
        totalFleet: mockFleetVehicles.length,
        activeVehicles: 3,
        inactiveVehicles: 2,
        avgSpeedKmH: 34,
        avgETAMinutes: 8,
      };
    }
  },
};
