import React from 'react';
import { History, Download, FileText, CheckCircle, Clock } from 'lucide-react';
import { useReportHistory } from '../../../hooks/useReports';

export const ReportHistory: React.FC = () => {
  const { data: historyList, isLoading } = useReportHistory();

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-xs mt-8">
      <div className="flex items-center justify-between pb-3.5 mb-4 border-b border-slate-100 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <History className="w-4.5 h-4.5 text-indigo-600 dark:text-indigo-400" />
          <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
            Generated Report History & Audit Trail
          </h3>
        </div>
        <span className="text-xs font-semibold text-slate-400">
          {historyList?.length || 0} Saved Archives
        </span>
      </div>

      {isLoading ? (
        <div className="py-8 text-center text-xs text-slate-400 animate-pulse">
          Loading report history...
        </div>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-slate-100 dark:border-slate-800">
          <table className="w-full text-left text-xs text-slate-700 dark:text-slate-300">
            <thead className="bg-slate-100/80 dark:bg-slate-800/80 text-slate-600 dark:text-slate-300 font-bold uppercase tracking-wider text-[10px]">
              <tr>
                <th className="px-3.5 py-3">Report ID & Title</th>
                <th className="px-3.5 py-3">Generated By</th>
                <th className="px-3.5 py-3">Generated Time</th>
                <th className="px-3.5 py-3">Downloads</th>
                <th className="px-3.5 py-3">File Formats</th>
                <th className="px-3.5 py-3">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-medium">
              {historyList && historyList.length > 0 ? (
                historyList.map((item) => (
                  <tr key={item.id} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/40 transition-colors">
                    <td className="px-3.5 py-3">
                      <div className="font-bold text-slate-900 dark:text-slate-100 flex items-center gap-1.5">
                        <FileText className="w-3.5 h-3.5 text-indigo-500" />
                        <span>{item.title}</span>
                      </div>
                      <span className="text-[10px] text-slate-400 font-mono">{item.id} • {item.recordCount} Records</span>
                    </td>
                    <td className="px-3.5 py-3 text-slate-600 dark:text-slate-400">{item.generatedBy}</td>
                    <td className="px-3.5 py-3 whitespace-nowrap text-slate-500 dark:text-slate-400">
                      <div className="flex items-center gap-1">
                        <Clock className="w-3 h-3 text-slate-400" />
                        <span>{item.generatedAt}</span>
                      </div>
                    </td>
                    <td className="px-3.5 py-3 font-semibold text-slate-800 dark:text-slate-200">
                      <div className="flex items-center gap-1">
                        <Download className="w-3 h-3 text-indigo-500" />
                        <span>{item.downloadedCount} times</span>
                      </div>
                    </td>
                    <td className="px-3.5 py-3">
                      <div className="flex items-center gap-1">
                        {item.fileTypes.map((ft, fIdx) => (
                          <span
                            key={fIdx}
                            className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300"
                          >
                            {ft}
                          </span>
                        ))}
                      </div>
                    </td>
                    <td className="px-3.5 py-3">
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                        <CheckCircle className="w-3 h-3" />
                        {item.status}
                      </span>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center text-slate-400">
                    No report history archives yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
